version: '3.8'
services:
  app:
    build: .
    container_name: mbg-backend
    tty: true
    stdin_open: true
    restart: always
    # env_file:
    #   - .env.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_CHANNELBINDING=${DB_CHANNELBINDING}
      - JWT_SECRET=${JWT_SECRET}
      - TZ=Asia/Jakarta
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true