version: '3.8'
services:
  app:
    build: .
    container_name: mbg-backend
    restart: always
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_DIALECT=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mbg_prod
      - DB_USER=mbguser
      - DB_PASS=mbgpass
    networks:
      - internal
  db:
    image: postgres:15-alpine
    container_name: mbg-postgres
    restart: always
    environment:
      POSTGRES_DB: mbg_prod
      POSTGRES_USER: mbguser
      POSTGRES_PASSWORD: mbgpass
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
volumes:
  pgdata:
