version: '3.8'
services:
  db:
    image: postgres:16
    container_name: mbg-postgres
    restart: always
    environment:
      POSTGRES_DB: mbg_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  api:
    build: .
    container_name: mbg-backend
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - JWT_SECRET=${JWT_SECRET:-dev-secret-change-me}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/mbg_dev
      - DB_ENGINE=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mbg_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CORS_WHITELIST=${CORS_WHITELIST:-http://localhost:8000,http://127.0.0.1:8000,https://mbg.mrt.qzz.io}
      - SEED_MASTER_ADMIN=${SEED_MASTER_ADMIN:-true}
      - SECURITY_ENABLED=${SECURITY_ENABLED:-false}
      - CORS_ENABLED=${CORS_ENABLED:-false}
    depends_on:
      - db
    # ports:
    #   - "8000:8000"
    volumes:
      - mbg-data:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - cloudflared-private
      - internal

networks:
  cloudflared-private:
    external: true
  internal:
    driver: bridge

volumes:
  mbg-data:
  pgdata: