version: "3.9"

services:
  app:
    build: .
    container_name: mbg_fastapi
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_ENGINE: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mbg_dev
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - internal

  db:
    image: postgres:15
    container_name: mbg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mbg_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge