version: '3.8'
services:
  api:
    build: .
    container_name: mbg-backend-fastapi
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - JWT_SECRET=${JWT_SECRET:-dev-secret-change-me}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./mbg_fastapi_dev.db}
      - CORS_WHITELIST=${CORS_WHITELIST:-http://localhost:8000,http://127.0.0.1:8000}
      - SEED_MASTER_ADMIN=${SEED_MASTER_ADMIN:-true}
    # ports:
    #   - "8000:8000"
    volumes:
      - mbg-data:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - cloudflared-private

networks:
  cloudflared-private:
    external: true

volumes:
  mbg-data: