name: Deploy to Portainer

on:
  push:
    branches:
      - fastapi

jobs:
  trigger-portainer:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portainer Webhook
        run: |
          curl -X POST https://portainer.giovanc.xyz/api/stacks/webhooks/6757159a-8367-4a8e-85d6-714e89e6afaa
